version: 2

project_name: agent

before:
  hooks:
    # Validate that generated files are up to date (prevents +dirty version suffix)
    - sh -c "make generate manifests fmt && go mod tidy && git diff --exit-code || (echo 'ERROR: Generated files are out of date. Run make generate manifests fmt && go mod tidy, then commit the changes.' && exit 1)"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "docker.io/apptrail/agent:{{ .Version }}-amd64"
      - "docker.io/apptrail/agent:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/apptrail-sh/agent:{{ .Version }}-amd64"
      - "ghcr.io/apptrail-sh/agent:{{ .Major }}.{{ .Minor }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.description=AppTrail Agent"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "docker.io/apptrail/agent:{{ .Version }}-arm64v8"
      - "docker.io/apptrail/agent:{{ .Major }}.{{ .Minor }}-arm64v8"
      - "ghcr.io/apptrail-sh/agent:{{ .Version }}-arm64v8"
      - "ghcr.io/apptrail-sh/agent:{{ .Major }}.{{ .Minor }}-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.description=AppTrail Agent"

docker_manifests:
  - name_template: "docker.io/apptrail/agent:{{ .Version }}"
    image_templates:
      - docker.io/apptrail/agent:{{ .Version }}-amd64
      - docker.io/apptrail/agent:{{ .Version }}-arm64v8
  - name_template: "docker.io/apptrail/agent:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - docker.io/apptrail/agent:{{ .Major }}.{{ .Minor }}-amd64
      - docker.io/apptrail/agent:{{ .Major }}.{{ .Minor }}-arm64v8
  - name_template: "ghcr.io/apptrail-sh/agent:{{ .Version }}"
    image_templates:
      - ghcr.io/apptrail-sh/agent:{{ .Version }}-amd64
      - ghcr.io/apptrail-sh/agent:{{ .Version }}-arm64v8
  - name_template: "ghcr.io/apptrail-sh/agent:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - ghcr.io/apptrail-sh/agent:{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/apptrail-sh/agent:{{ .Major }}.{{ .Minor }}-arm64v8

release:
  extra_files:
    - glob: config/crd/bases/*.yaml

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
