/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"context"
	"crypto/tls"
	"flag"
	"os"

	"github.com/apptrail-sh/agent/internal/hooks"
	"github.com/apptrail-sh/agent/internal/hooks/controlplane"
	"github.com/apptrail-sh/agent/internal/hooks/pubsub"
	"github.com/apptrail-sh/agent/internal/hooks/slack"
	"github.com/apptrail-sh/agent/internal/model"

	"github.com/apptrail-sh/agent/internal/reconciler"

	// Import all Kubernetes client auth plugins (e.g. Azure, GCP, OIDC, etc.)
	// to ensure that exec-entrypoint and run can make use of them.
	_ "k8s.io/client-go/plugin/pkg/client/auth"

	"k8s.io/apimachinery/pkg/runtime"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/healthz"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
	"sigs.k8s.io/controller-runtime/pkg/metrics/filters"
	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"
	"sigs.k8s.io/controller-runtime/pkg/webhook"

	apptrailv1alpha1 "github.com/apptrail-sh/agent/api/v1alpha1"
	// +kubebuilder:scaffold:imports
)

var (
	scheme   = runtime.NewScheme()
	setupLog = ctrl.Log.WithName("setup")
)

func init() {
	utilruntime.Must(clientgoscheme.AddToScheme(scheme))

	utilruntime.Must(apptrailv1alpha1.AddToScheme(scheme))
	// +kubebuilder:scaffold:scheme
}

func main() {
	var metricsAddr string
	var enableLeaderElection bool
	var probeAddr string
	var secureMetrics bool
	var enableHTTP2 bool
	var tlsOpts []func(*tls.Config)
	var slackWebhookURL string
	var controlPlaneURL string
	var clusterID string
	var environment string
	var pubsubTopic string
	flag.StringVar(&metricsAddr, "metrics-bind-address", ":8080", "The address the metrics endpoint binds to. "+
		"Use :8443 for HTTPS or :8080 for HTTP, or leave as 0 to disable the metrics service.")
	flag.StringVar(&probeAddr, "health-probe-bind-address", ":8081", "The address the probe endpoint binds to.")
	flag.BoolVar(&enableLeaderElection, "leader-elect", false,
		"Enable leader election for controller manager. "+
			"Enabling this will ensure there is only one active controller manager.")
	flag.BoolVar(&secureMetrics, "metrics-secure", false,
		"If set, the metrics endpoint is served securely via HTTPS. Use --metrics-secure=false to use HTTP instead.")
	flag.BoolVar(&enableHTTP2, "enable-http2", false,
		"If set, HTTP/2 will be enabled for the metrics and webhook servers")
	flag.StringVar(&slackWebhookURL, "slack-webhook-url", "", "The URL to send slack notifications to")
	flag.StringVar(&controlPlaneURL, "controlplane-url", "",
		"The URL of the AppTrail Control Plane (e.g., http://controlplane:3000/api/v1/events)")
	flag.StringVar(&clusterID, "cluster-id", os.Getenv("CLUSTER_ID"),
		"Unique identifier for this cluster (e.g., staging.stg01)")
	flag.StringVar(&environment, "environment", os.Getenv("ENVIRONMENT"),
		"Environment for events without namespace mapping (optional)")
	flag.StringVar(&pubsubTopic, "pubsub-topic", os.Getenv("PUBSUB_TOPIC"),
		"Google Cloud Pub/Sub topic path (projects/<project>/topics/<topic>)")

	opts := zap.Options{
		Development: true,
	}
	opts.BindFlags(flag.CommandLine)
	flag.Parse()

	ctrl.SetLogger(zap.New(zap.UseFlagOptions(&opts)))

	// if the enable-http2 flag is false (the default), http/2 should be disabled
	// due to its vulnerabilities. More specifically, disabling http/2 will
	// prevent from being vulnerable to the HTTP/2 Stream Cancellation and
	// Rapid Reset CVEs. For more information see:
	// - https://github.com/advisories/GHSA-qppj-fm5r-hxr3
	// - https://github.com/advisories/GHSA-4374-p667-p6c8
	disableHTTP2 := func(c *tls.Config) {
		setupLog.Info("disabling http/2")
		c.NextProtos = []string{"http/1.1"}
	}

	if !enableHTTP2 {
		tlsOpts = append(tlsOpts, disableHTTP2)
	}

	webhookServer := webhook.NewServer(webhook.Options{
		TLSOpts: tlsOpts,
	})

	// Metrics endpoint is enabled in 'config/default/kustomization.yaml'. The Metrics options configure the server.
	// More info:
	// - https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.19.0/pkg/metrics/server
	// - https://book.kubebuilder.io/reference/metrics.html
	metricsServerOptions := metricsserver.Options{
		BindAddress:   metricsAddr,
		SecureServing: secureMetrics,
		// TODO(user): TLSOpts is used to allow configuring the TLS config used for the server. If certificates are
		// not provided, self-signed certificates will be generated by default. This option is not recommended for
		// production environments as self-signed certificates do not offer the same level of trust and security
		// as certificates issued by a trusted Certificate Authority (CA). The primary risk is potentially allowing
		// unauthorized access to sensitive metrics data. Consider replacing with CertDir, CertName, and KeyName
		// to provide certificates, ensuring the server communicates using trusted and secure certificates.
		TLSOpts: tlsOpts,
	}

	if secureMetrics {
		// FilterProvider is used to protect the metrics endpoint with authn/authz.
		// These configurations ensure that only authorized users and service accounts
		// can access the metrics endpoint. The RBAC are configured in 'config/rbac/kustomization.yaml'. More info:
		// https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.19.0/pkg/metrics/filters#WithAuthenticationAndAuthorization
		metricsServerOptions.FilterProvider = filters.WithAuthenticationAndAuthorization
	}

	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme:                 scheme,
		Metrics:                metricsServerOptions,
		WebhookServer:          webhookServer,
		HealthProbeBindAddress: probeAddr,
		LeaderElection:         enableLeaderElection,
		LeaderElectionID:       "ce02bd06.apptrail.sh",
		// LeaderElectionReleaseOnCancel defines if the leader should step down voluntarily
		// when the Manager ends. This requires the binary to immediately end when the
		// Manager is stopped, otherwise, this setting is unsafe. Setting this significantly
		// speeds up voluntary leader transitions as the new leader don't have to wait
		// LeaseDuration time first.
		//
		// In the default scaffold provided, the program ends immediately after
		// the manager stops, so would be fine to enable this option. However,
		// if you are doing or is intended to do any operation such as perform cleanups
		// after the manager stops then its usage might be unsafe.
		// LeaderElectionReleaseOnCancel: true,
	})
	if err != nil {
		setupLog.Error(err, "unable to start manager")
		os.Exit(1)
	}

	publisherChan := make(chan model.WorkloadUpdate, 100)

	var publishers = []hooks.EventPublisher{}

	// Register Slack publisher if configured
	if slackWebhookURL != "" {
		slackPublisher := slack.NewSlackPublisher(slackWebhookURL)
		publishers = append(publishers, slackPublisher)
		setupLog.Info("Slack publisher enabled", "webhook", slackWebhookURL)
	}

	// Register Control Plane publisher if configured
	if controlPlaneURL != "" {
		if clusterID == "" {
			setupLog.Error(nil, "cluster-id is required when controlplane-url is set")
			os.Exit(1)
		}
		cpPublisher := controlplane.NewHTTPPublisher(controlPlaneURL, clusterID, environment)
		publishers = append(publishers, cpPublisher)
		setupLog.Info("Control Plane publisher enabled",
			"endpoint", controlPlaneURL,
			"clusterID", clusterID,
			"environment", environment)
	}

	// Register Google Pub/Sub publisher if configured
	if pubsubTopic != "" {
		if clusterID == "" {
			setupLog.Error(nil, "cluster-id is required when pubsub is enabled")
			os.Exit(1)
		}
		ctx := context.Background()
		pubsubPublisher, err := pubsub.NewPubSubPublisher(ctx, pubsubTopic, clusterID, environment)
		if err != nil {
			setupLog.Error(err, "unable to create Pub/Sub publisher",
				"hint", "Ensure valid credentials via Workload Identity, GOOGLE_APPLICATION_CREDENTIALS, or gcloud auth")
			os.Exit(1)
		}
		publishers = append(publishers, pubsubPublisher)
		setupLog.Info("Google Pub/Sub publisher enabled",
			"topic", pubsubTopic,
			"clusterID", clusterID,
			"environment", environment)
	}

	if len(publishers) == 0 {
		setupLog.Info("No event publishers configured, events will only be exported as metrics")
	}

	publisherQueue := hooks.NewEventPublisherQueue(publisherChan, publishers)
	go publisherQueue.Loop()

	// Get the namespace where the controller is running
	// This is used to store WorkloadRolloutState CRDs
	controllerNamespace := os.Getenv("POD_NAMESPACE")
	if controllerNamespace == "" {
		controllerNamespace = "apptrail-system" // Default namespace
		setupLog.Info("POD_NAMESPACE not set, using default", "namespace", controllerNamespace)
	}

	// Setup Deployment reconciler
	deploymentReconciler := reconciler.NewDeploymentReconciler(
		mgr.GetClient(),
		mgr.GetScheme(),
		mgr.GetEventRecorderFor("apptrail-agent"),
		publisherChan,
		controllerNamespace)

	if err = deploymentReconciler.SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "AppTrailDeployment")
		os.Exit(1)
	}

	// Setup StatefulSet reconciler
	statefulSetReconciler := reconciler.NewStatefulSetReconciler(
		mgr.GetClient(),
		mgr.GetScheme(),
		mgr.GetEventRecorderFor("apptrail-agent"),
		publisherChan,
		controllerNamespace)

	if err = statefulSetReconciler.SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "AppTrailStatefulSet")
		os.Exit(1)
	}

	// Setup DaemonSet reconciler
	daemonSetReconciler := reconciler.NewDaemonSetReconciler(
		mgr.GetClient(),
		mgr.GetScheme(),
		mgr.GetEventRecorderFor("apptrail-agent"),
		publisherChan,
		controllerNamespace)

	if err = daemonSetReconciler.SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "AppTrailDaemonSet")
		os.Exit(1)
	}

	// +kubebuilder:scaffold:builder

	if err := mgr.AddHealthzCheck("healthz", healthz.Ping); err != nil {
		setupLog.Error(err, "unable to set up health check")
		os.Exit(1)
	}
	if err := mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {
		setupLog.Error(err, "unable to set up ready check")
		os.Exit(1)
	}

	setupLog.Info("starting manager")
	if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {
		setupLog.Error(err, "problem running manager")
		os.Exit(1)
	}
}
